/**
 * llamacpp-trainer.ts — ADR-0009 Phase 2
 *
 * Cross-platform QLoRA fine-tuning adapter using HuggingFace peft + transformers.
 *
 * Two execution paths, same Python script:
 *   llamacpp-cuda  — NVIDIA GPU detected; uses bitsandbytes 4-bit quantization + CUDA
 *   llamacpp-cpu   — No GPU; uses CPU training (slow but correct, good for testing)
 *
 * The "llamacpp" naming follows ADR-0009 conventions. The actual Python stack is
 * peft + transformers + bitsandbytes (not the llama.cpp C++ binary) because:
 *  1. It produces .safetensors adapters compatible with the rest of the pipeline
 *  2. The same code works on CPU and CUDA — only device selection differs
 *  3. CPU training validates correctness on any hardware (including M1 for CI)
 *
 * Requirements (user must install):
 *   pip install peft transformers bitsandbytes accelerate datasets
 *   # CUDA only — bitsandbytes requires CUDA 11.x+ for 4-bit quantization
 *   # CPU mode works without a GPU (slow)
 *
 * Output:
 *   <adapterDir>/adapter.safetensors     — LoRA weights (peft format)
 *   <adapterDir>/adapter_config.json     — LoRA config
 */

import { spawn } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import type { TrainingBatch } from "./trajectory-buffer.js";

export interface LlamaCppTrainOptions {
  baseModel: string;
  batch: TrainingBatch;
  adapterDir: string;
  backend: "cpu" | "cuda";
  loraRank?: number;
  loraAlpha?: number;
  epochs?: number;
  batchSize?: number;
  learningRate?: number;
  dryRun?: boolean;
  onProgress?: (msg: string) => void;
}

export interface LlamaCppTrainResult {
  success: boolean;
  adapterPath?: string;
  durationMs: number;
  error?: string;
}

// ── Data preparation ──────────────────────────────────────────────────────────

/**
 * Write trajectory batch as a JSONL file in peft/SFT format.
 * Each line: {"prompt": "...", "response": "..."}
 */
async function writePeftTrainData(batch: TrainingBatch, outPath: string): Promise<number> {
  const lines: string[] = [];

  for (const entry of batch.entries) {
    try {
      const content = await fs.readFile(entry.jsonlPath, "utf8");
      const events = content
        .trim()
        .split("\n")
        .filter(Boolean)
        .map((l) => JSON.parse(l) as { type?: string; message?: { content?: unknown } });

      const prompt = entry.meta.prompt ?? "";
      let response = "";

      for (const ev of events) {
        if (ev.type === "assistant") {
          const c = ev.message?.content;
          if (typeof c === "string" && c.trim()) {
            response = c.slice(0, 2000);
            break;
          } else if (Array.isArray(c)) {
            for (const block of c) {
              const b = block as { type?: string; text?: string };
              if (b.type === "text" && b.text?.trim()) {
                response = b.text.slice(0, 2000);
                break;
              }
            }
            if (response) break;
          }
        }
      }

      if (prompt && response) {
        lines.push(JSON.stringify({ prompt, response }));
      }
    } catch { /* skip malformed trajectory */ }
  }

  await fs.writeFile(outPath, lines.join("\n") + "\n", "utf8");
  return lines.length;
}

// ── Training script generator ─────────────────────────────────────────────────

/**
 * Generate a self-contained Python training script using peft + transformers.
 * The same script runs on CPU and CUDA — only the device and quantization config differ.
 */
function generatePeftScript(opts: LlamaCppTrainOptions, dataFile: string): string {
  const useCuda = opts.backend === "cuda";
  const loraRank = opts.loraRank ?? 16;
  const loraAlpha = opts.loraAlpha ?? 32;
  const epochs = opts.epochs ?? 1;
  const batchSize = useCuda ? (opts.batchSize ?? 4) : 1; // CPU: batch=1 to limit RAM
  const lr = opts.learningRate ?? 2e-5;

  return `#!/usr/bin/env python3
"""
OMLS local training script (peft + transformers) — generated by orager
Backend: ${opts.backend}
"""
import json, os, sys
from pathlib import Path

import torch
from datasets import Dataset
from peft import LoraConfig, get_peft_model, TaskType
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
)
${useCuda ? "from transformers import BitsAndBytesConfig" : ""}

ADAPTER_DIR = "${opts.adapterDir.replace(/\\/g, "/")}"
BASE_MODEL  = "${opts.baseModel}"
DATA_FILE   = "${dataFile.replace(/\\/g, "/")}"
DEVICE      = "cuda" if ${useCuda ? "True" : "False"} and torch.cuda.is_available() else "cpu"

print(f"[peft] device={DEVICE} base_model={BASE_MODEL}", flush=True)

# ── Load data ─────────────────────────────────────────────────────────────────
records = []
with open(DATA_FILE) as f:
    for line in f:
        line = line.strip()
        if line:
            r = json.loads(line)
            records.append({"text": r["prompt"] + "\\n" + r["response"]})

if not records:
    print("[peft] ERROR: no training records found", flush=True)
    sys.exit(1)

print(f"[peft] {len(records)} training samples loaded", flush=True)
dataset = Dataset.from_list(records)

# ── Load tokenizer ────────────────────────────────────────────────────────────
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

def tokenize(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=512,
        padding="max_length",
    )

tokenized = dataset.map(tokenize, batched=True, remove_columns=["text"])

# ── Load model ────────────────────────────────────────────────────────────────
${useCuda ? `
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)
model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
)
` : `
model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.float32,
    device_map="cpu",
    trust_remote_code=True,
    low_cpu_mem_usage=True,
)
`}

# ── Apply LoRA ────────────────────────────────────────────────────────────────
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=${loraRank},
    lora_alpha=${loraAlpha},
    lora_dropout=0.05,
    bias="none",
    target_modules=["q_proj", "v_proj"],
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# ── Train ────────────────────────────────────────────────────────────────────
training_args = TrainingArguments(
    output_dir=ADAPTER_DIR,
    num_train_epochs=${epochs},
    per_device_train_batch_size=${batchSize},
    learning_rate=${lr},
    fp16=${useCuda ? "True" : "False"},
    logging_steps=10,
    save_steps=100,
    save_total_limit=1,
    report_to="none",
    dataloader_num_workers=0,
    no_cuda=${useCuda ? "False" : "True"},
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
)

print("[peft] starting training…", flush=True)
trainer.train()

# ── Save adapter ─────────────────────────────────────────────────────────────
Path(ADAPTER_DIR).mkdir(parents=True, exist_ok=True)
model.save_pretrained(ADAPTER_DIR)
print(f"[peft] adapter saved to {ADAPTER_DIR}", flush=True)
`;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Run peft QLoRA fine-tuning on the given trajectory batch.
 *
 * Spawns a generated Python script as a subprocess and streams output
 * to `onProgress`. Returns the adapter path on success.
 *
 * Dry-run mode validates setup and prints estimated duration without training.
 * CPU path is slow (hours for 7B) but functionally identical to CUDA for
 * correctness testing.
 */
export async function trainWithLlamaCpp(opts: LlamaCppTrainOptions): Promise<LlamaCppTrainResult> {
  const startMs = Date.now();
  const log = opts.onProgress ?? (() => {});

  await fs.mkdir(opts.adapterDir, { recursive: true });

  // ── Data preparation ────────────────────────────────────────────────────────
  const dataFile = path.join(opts.batch.batchDir, "peft_train.jsonl");
  let sampleCount: number;
  try {
    sampleCount = await writePeftTrainData(opts.batch, dataFile);
  } catch (err) {
    return { success: false, durationMs: Date.now() - startMs, error: `data prep failed: ${err}` };
  }

  if (sampleCount === 0) {
    return { success: false, durationMs: Date.now() - startMs, error: "no usable training samples in batch" };
  }

  log(`[peft/${opts.backend}] prepared ${sampleCount} training samples → ${dataFile}\n`);

  // ── Dry-run path ────────────────────────────────────────────────────────────
  if (opts.dryRun) {
    const estimate = opts.backend === "cuda" ? "8–12 min on RTX 3080" : "2–8 hours on CPU";
    log(`[peft/${opts.backend}] dry-run: would train ${opts.baseModel} on ${sampleCount} samples\n`);
    log(`[peft/${opts.backend}] dry-run: adapter output → ${opts.adapterDir}\n`);
    log(`[peft/${opts.backend}] dry-run: estimated duration: ${estimate}\n`);
    return { success: true, durationMs: Date.now() - startMs };
  }

  // ── Write + run training script ─────────────────────────────────────────────
  const scriptPath = path.join(opts.batch.batchDir, "peft_train.py");
  await fs.writeFile(scriptPath, generatePeftScript(opts, dataFile), "utf8");
  log(`[peft/${opts.backend}] python3 ${scriptPath}\n`);

  return new Promise((resolve) => {
    const proc = spawn("python3", [scriptPath], {
      stdio: ["ignore", "pipe", "pipe"],
      env: { ...process.env },
    });

    proc.stdout?.on("data", (chunk: Buffer) => log(`[peft/${opts.backend}] ${chunk.toString()}`));
    proc.stderr?.on("data", (chunk: Buffer) => log(`[peft/${opts.backend}] ${chunk.toString()}`));

    proc.on("close", (code) => {
      const durationMs = Date.now() - startMs;
      if (code === 0) {
        const adapterPath = path.join(opts.adapterDir, "adapter.safetensors");
        log(`[peft/${opts.backend}] training complete (${Math.round(durationMs / 1000)}s) → ${adapterPath}\n`);
        resolve({ success: true, adapterPath, durationMs });
      } else {
        resolve({
          success: false,
          durationMs,
          error: `peft training script exited with code ${code}. Run: pip install peft transformers bitsandbytes accelerate datasets`,
        });
      }
    });

    proc.on("error", (err) => {
      resolve({
        success: false,
        durationMs: Date.now() - startMs,
        error: `failed to spawn python3: ${err.message}`,
      });
    });
  });
}
