/**
 * training-pipeline.ts — ADR-0007
 *
 * 8-step OMLS training pipeline orchestrator:
 *
 *   Step 1: Package trajectory batch
 *   Step 2: PRM scoring
 *   Step 3: Spin up VPS GPU
 *   Step 4: Run GRPO/OPSD training
 *   Step 5: Download adapter + terminate GPU
 *   Step 6: Upload adapter to Together AI
 *   Step 7: Atomic endpoint swap
 *   Step 8: Log and notify
 *
 * Called by the scheduler when idle + buffer conditions are met.
 * Also called directly by `orager skill-train --rl`.
 */

import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import type { OmlsConfig } from "../types.js";
import {
  scanDistillableBuffer,
  packageBatch,
  markBatchTrained,
  getCurrentSkillGeneration,
  getTrainingDir,
  type TrainingBatch,
} from "./trajectory-buffer.js";
import { scoreTrajectory } from "./prm-scorer.js";
import { launchInstance, terminateInstance, scpUpload, scpDownload, sshExec, type VpsInstance } from "./vps-client.js";
import { uploadAdapter, swapEndpoint, getAdaptersDir } from "./together-hosting.js";
import { isSupportedBaseModel, DEFAULT_BASE_MODEL_ID } from "./supported-models.js";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface PipelineResult {
  success: boolean;
  version?: number;
  endpoint?: string;
  costUsd?: number;
  durationMs?: number;
  error?: string;
  steps: Array<{ step: string; status: "ok" | "error" | "skipped"; durationMs: number; detail?: string }>;
}

export interface PipelineOptions {
  dryRun?: boolean;
  backendOverride?: string;
  apiKey: string;
  cfg: OmlsConfig;
  onProgress?: (msg: string) => void;
}

// ── Unsloth training script generator ────────────────────────────────────────

function generateTrainingScript(cfg: OmlsConfig, batchDir: string): string {
  const training = cfg.rl?.training ?? {};
  const baseModel = training.baseModel ?? DEFAULT_BASE_MODEL_ID;
  const method = training.method ?? "auto";
  const loraRank = training.loraRank ?? 16;
  const loraAlpha = training.loraAlpha ?? 32;
  const epochs = training.epochs ?? 1;
  const batchSize = training.batchSize ?? 4;
  const lr = training.learningRate ?? 2e-5;

  // Determine training method based on batch composition
  // auto: use OPSD if teacher responses are available, else GRPO
  const methodCode = method === "grpo" ? '"grpo"'
    : method === "opsd" ? '"opsd"'
    : '("opsd" if has_teacher_responses else "grpo")';

  return `#!/usr/bin/env python3
"""
OMLS training script — generated by orager
"""
import json, os, glob, torch
from pathlib import Path
from unsloth import FastLanguageModel
from trl import GRPOTrainer, GRPOConfig

BATCH_DIR = "${batchDir}"
BASE_MODEL = "${baseModel}"
LORA_RANK = ${loraRank}
LORA_ALPHA = ${loraAlpha}
EPOCHS = ${epochs}
BATCH_SIZE = ${batchSize}
LR = ${lr}

# ── Load trajectories ──────────────────────────────────────────────────────────
trajectories = []
for meta_file in glob.glob(f"{BATCH_DIR}/trajectories/*.meta.json"):
    sid = Path(meta_file).stem.replace(".meta", "")
    jsonl_file = meta_file.replace(".meta.json", ".jsonl")
    with open(meta_file) as f:
        meta = json.load(f)
    with open(jsonl_file) as f:
        events = [json.loads(l) for l in f if l.strip()]
    trajectories.append({"meta": meta, "events": events, "sid": sid})

has_teacher_responses = any(t["meta"].get("distillable") for t in trajectories)
METHOD = ${methodCode}
print(f"Training method: {METHOD} ({len(trajectories)} trajectories)")

# ── Load PRM scores ────────────────────────────────────────────────────────────
scores_file = os.path.join(BATCH_DIR, "prm_scores.json")
prm_scores = {}
if os.path.exists(scores_file):
    with open(scores_file) as f:
        prm_scores = json.load(f)

# ── Load model ────────────────────────────────────────────────────────────────
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=BASE_MODEL,
    max_seq_length=4096,
    dtype=None,
    load_in_4bit=True,
)
model = FastLanguageModel.get_peft_model(
    model,
    r=LORA_RANK,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
    lora_alpha=LORA_ALPHA,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=42,
)

# ── Build training dataset ────────────────────────────────────────────────────
def build_prompt(events):
    parts = []
    for ev in events:
        if ev.get("type") == "assistant":
            for block in (ev.get("message", {}).get("content") or []):
                if block.get("type") == "text":
                    parts.append(block["text"][:500])
    return "\\n".join(parts[:5])

dataset = []
for traj in trajectories:
    meta = traj["meta"]
    prompt = meta.get("prompt", "")
    response = build_prompt(traj["events"])
    sid = traj["sid"]
    reward = prm_scores.get(sid, {}).get("weighted_score", 0.5)

    if METHOD == "opsd" and meta.get("teacherModel"):
        # OPSD: token-level supervision from teacher response
        dataset.append({
            "prompt": prompt,
            "chosen": response,
            "reward": reward,
            "teacher_model": meta.get("teacherModel", ""),
        })
    else:
        # GRPO: reward-weighted policy gradient
        dataset.append({"prompt": prompt, "response": response, "reward": reward})

from datasets import Dataset
ds = Dataset.from_list(dataset)

# ── Train ─────────────────────────────────────────────────────────────────────
training_args = GRPOConfig(
    output_dir="/root/adapter",
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    learning_rate=LR,
    logging_steps=10,
    save_strategy="epoch",
    fp16=not torch.cuda.is_bf16_supported(),
    bf16=torch.cuda.is_bf16_supported(),
    report_to="none",
)

trainer = GRPOTrainer(
    model=model,
    args=training_args,
    train_dataset=ds,
    tokenizer=tokenizer,
)
trainer.train()

# ── Save adapter ──────────────────────────────────────────────────────────────
model.save_pretrained_merged("/root/adapter", tokenizer)
print("Training complete. Adapter saved to /root/adapter")
`;
}

// ── Pipeline ──────────────────────────────────────────────────────────────────

export async function runTrainingPipeline(opts: PipelineOptions): Promise<PipelineResult> {
  const { dryRun = false, cfg, apiKey, onProgress } = opts;
  const log = onProgress ?? ((msg: string) => process.stderr.write(`[omls] ${msg}\n`));

  const result: PipelineResult = { success: false, steps: [] };
  const startMs = Date.now();

  // ── Mode guard ─────────────────────────────────────────────────────────────
  const mode = cfg.mode ?? "auto";
  if (mode === "prompt") {
    const msg = `[omls] mode=prompt: LoRA training is disabled. Set omls.mode to "lora" or "auto" to enable.`;
    process.stderr.write(msg + "\n");
    result.error = msg;
    return result;
  }

  // ── Base model validation ──────────────────────────────────────────────────
  // Only one base model is active at a time. All adapters are hard-tied to the
  // base model they were trained on — switching discards existing adapters.
  const configuredBaseModel = cfg.rl?.training?.baseModel ?? DEFAULT_BASE_MODEL_ID;
  if (!isSupportedBaseModel(configuredBaseModel)) {
    const msg = `[omls] Unsupported base model: "${configuredBaseModel}". ` +
      `Run \`orager omls models\` to see the supported list.`;
    process.stderr.write(msg + "\n");
    result.error = msg;
    return result;
  }

  // Warn if the base model changed since the last training run — existing
  // adapters will be incompatible with the new model.
  try {
    const logPath = `${os.homedir()}/.orager/omls.log`;
    const { readFileSync } = await import("node:fs");
    if (readFileSync(logPath, "utf8").trim()) {
      const lines = readFileSync(logPath, "utf8").trim().split("\n");
      const lastRun = JSON.parse(lines[lines.length - 1]!);
      const prevModel: string | undefined = lastRun.baseModel;
      if (prevModel && prevModel !== configuredBaseModel) {
        process.stderr.write(
          `[omls] ⚠️  Base model changed: "${prevModel}" → "${configuredBaseModel}". ` +
          `Existing adapters trained on "${prevModel}" are incompatible and will no longer be loaded.\n`,
        );
      }
    }
  } catch { /* no prior log — first run, no warning needed */ }

  let instance: VpsInstance | null = null;
  let batch: TrainingBatch | null = null;

  const step = (name: string) => ({ name, startMs: Date.now() });
  const ok = (s: ReturnType<typeof step>, detail?: string) => {
    result.steps.push({ step: s.name, status: "ok", durationMs: Date.now() - s.startMs, detail });
  };
  const fail = (s: ReturnType<typeof step>, detail: string) => {
    result.steps.push({ step: s.name, status: "error", durationMs: Date.now() - s.startMs, detail });
    result.error = detail;
  };

  try {
    // ── Step 1: Package batch ────────────────────────────────────────────────
    const s1 = step("package_batch");
    log("Step 1/8: packaging trajectory batch…");
    const skillGen = await getCurrentSkillGeneration();
    const entries = await scanDistillableBuffer(skillGen);
    const minBatch = cfg.minBatchSize ?? 8;
    if (entries.length < minBatch) {
      fail(s1, `buffer too small (${entries.length}/${minBatch})`);
      return result;
    }
    batch = await packageBatch(entries);
    ok(s1, `${batch.entries.length} trajectories → ${batch.batchDir}`);

    if (dryRun) {
      log(`[dry-run] Would train on ${batch.entries.length} trajectories.`);
      log(`[dry-run] Estimated cost: ~$1.25 (VPS) + ~$0.05 (PRM scoring) = ~$1.30`);
      result.success = true;
      result.steps.push({ step: "dry_run", status: "ok", durationMs: 0 });
      return result;
    }

    // ── Step 2: PRM scoring ──────────────────────────────────────────────────
    const s2 = step("prm_scoring");
    log("Step 2/8: scoring trajectories with PRM judge…");
    const judgeModel = cfg.teacherModels?.[0] ?? "deepseek/deepseek-r1";
    const prmScores: Record<string, { mean_score: number; weighted_score: number }> = {};
    for (const entry of batch.entries) {
      const scored = await scoreTrajectory(entry.jsonlPath, entry.meta, judgeModel, apiKey);
      prmScores[entry.sessionId] = {
        mean_score: scored.meanScore,
        weighted_score: scored.weightedScore,
      };
    }
    await fs.writeFile(
      path.join(batch.batchDir, "prm_scores.json"),
      JSON.stringify(prmScores, null, 2),
      "utf8",
    );
    ok(s2, `scored ${Object.keys(prmScores).length} trajectories`);

    // ── Step 3: Spin up VPS ───────────────────────────────────────────────────
    const s3 = step("vps_launch");
    log("Step 3/8: launching VPS GPU instance…");
    instance = await launchInstance(cfg);
    ok(s3, `${instance.backend} instance ${instance.id} @ ${instance.host}:${instance.port}`);

    // ── Step 4: Upload bundle + run training ──────────────────────────────────
    const s4 = step("training");
    log("Step 4/8: uploading bundle and running GRPO/OPSD training…");

    // Install dependencies on remote
    sshExec(instance, "pip install unsloth trl datasets --quiet", 5 * 60 * 1000);

    // Upload batch directory
    scpUpload(batch.batchDir, instance, "/root/batch");

    // Write and upload training script
    const scriptContent = generateTrainingScript(cfg, "/root/batch");
    const scriptPath = path.join(batch.batchDir, "train.py");
    await fs.writeFile(scriptPath, scriptContent, "utf8");
    scpUpload(scriptPath, instance, "/root/train.py");

    // Run training (up to 4 hours)
    sshExec(instance, "python3 /root/train.py 2>&1 | tee /root/train.log");
    ok(s4, "training complete");

    // ── Step 5: Download adapter + terminate ─────────────────────────────────
    const s5 = step("download_terminate");
    log("Step 5/8: downloading adapter and terminating instance…");
    const adaptersDir = getAdaptersDir();
    const adapterVersion = (await import("./together-hosting.js").then((m) => m.listAdapterVersions())).length + 1;
    const localAdapterDir = path.join(adaptersDir, `v${adapterVersion}`);
    await fs.mkdir(localAdapterDir, { recursive: true });
    scpDownload(instance, "/root/adapter", localAdapterDir);

    // Create a tarball of the adapter for upload
    const { execFileSync } = await import("node:child_process");
    const tarPath = path.join(localAdapterDir, "adapter.tar.gz");
    execFileSync("tar", ["-czf", tarPath, "-C", localAdapterDir, "."], { timeout: 60_000 });

    await terminateInstance(instance, cfg);
    instance = null;
    ok(s5, `adapter saved to ${localAdapterDir}`);

    // ── Step 6: Upload to Together AI ────────────────────────────────────────
    const s6 = step("together_upload");
    log("Step 6/8: uploading adapter to Together AI…");
    const hosted = await uploadAdapter(localAdapterDir, configuredBaseModel, cfg);
    ok(s6, `endpoint: ${hosted.endpoint}`);

    // ── Step 7: Atomic endpoint swap ──────────────────────────────────────────
    const s7 = step("endpoint_swap");
    log("Step 7/8: swapping active model endpoint…");
    await swapEndpoint(hosted.endpoint);
    result.endpoint = hosted.endpoint;
    result.version = hosted.version;
    ok(s7, hosted.endpoint);

    // ── Step 8: Mark trained + log ────────────────────────────────────────────
    const s8 = step("finalize");
    log("Step 8/8: marking trajectories trained and logging…");
    await markBatchTrained(batch);

    const durationMs = Date.now() - startMs;
    result.durationMs = durationMs;
    result.success = true;

    // Write run log
    const logEntry = {
      timestamp: new Date().toISOString(),
      version: hosted.version,
      endpoint: hosted.endpoint,
      baseModel: configuredBaseModel,
      batchSize: batch.entries.length,
      durationMs,
      steps: result.steps,
    };
    const logDir = path.join(os.homedir(), ".orager");
    await fs.mkdir(logDir, { recursive: true });
    const logPath = path.join(logDir, "omls.log");
    await fs.appendFile(logPath, JSON.stringify(logEntry) + "\n", "utf8");

    ok(s8, `v${hosted.version} complete in ${Math.round(durationMs / 1000)}s`);
    log(`✅ RL update v${hosted.version} complete — endpoint: ${hosted.endpoint}`);

  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    process.stderr.write(`[omls] Pipeline error: ${msg}\n`);
    result.error = msg;

    // Always terminate instance on error to avoid billing
    if (instance) {
      try {
        await terminateInstance(instance, cfg);
        process.stderr.write("[omls] Instance terminated after error.\n");
      } catch { /* best effort */ }
    }
  }

  return result;
}
